[setup]
    STD_FUNCS = true

[system]
    LOG_LEVEL = "Warn"
    SCAN_RANGE = 5

[naming]
    DEFAULT_DICTIONARY = 'Dictionary'
    DEFAULT_DICTIONARY_DUPLICATED = 'DuplicatedDictionary'
    DEFAULT_DICTIONARY_MOCK = 'MockDictionary'
    DEFAULT_PROXY = 'Proxy'
    DEFAULT_PROXY_MOCK = 'MockProxy'
    DEFAULT_BUNDLE = 'Bundle'
    DEFAULT_FUNCTION = 'Function'
